# Generated by Django 5.2.6 on 2025-11-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_2FA',
            field=models.BooleanField(default=False),
        ),
    ]
