# Generated by Django 5.2.6 on 2025-11-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_amount_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='crypto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.crypto'),
        ),
    ]
