# Generated by Django 5.2.6 on 2025-11-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_history_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='converted_crypto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concerted_crypto', to='wallet.crypto'),
        ),
    ]
